version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
          PORT: 5001
          NODE_PATH: src/
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test:ci